# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Directory-Iterator
version:      1.000
version_from: lib/Directory/Iterator.pm
installdirs:  site
requires:
    Directory::Iterator::PP:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
